### PR TITLE
Release/2.3.0

### PR DESCRIPTION
**Pull request by Phanabani**
# 2.3.0
## Feature
- Support for React 17 and 18

## Code
- Use Parcel to build the library
- Use create-react-app for the `/dev_app/` testing page
    - This used to be located in `/dev/` and served with a complicated webpack setup
- Use yalc to build and test our library in `/dev_app/`
- Rewrite the testing page in typescript and with functional components
- Remove unmaintained dependency `react-hotkeys`
- Use GitHub Actions for CI (instead of Circle)

## Fix
- Rewrite a large portion of the README for clarity and fixing some mistakes

### CODE REVIEW

**Comment by Phanabani** [comment]
I was working on making this version 3.0.0, but rewriting the core components as functional react and typescript ended up taking a lot longer than I expected. I decided to split it into a minor release to be able to get changes released sooner, specifically compatibility with modern versions of Node and React.

I'm just waiting on resolution of #49, then I'll finish #42 and this should be ready to go!

**Comment by Phanabani** [comment]
I know a lot of files changed! To make it easier for you to review, check out the section I added in the readme about the [dev app](https://github.com/oxyno-zeta/react-editable-json-tree/blob/98be6a4552895ed3ebacb4f0eb924bbdb6464aa3/README.md#dev-app) and you can test it yourself!

**Comment by oxyno-zeta** [comment]
Hello @Phanabani ! 

What a nice work ! GG !
That will take some time to review as you can imagine ;).

A quick return to begin:
- prettier have been remove and not put back. Why ?
- the npm publish task have been removed. This was responsible of making the tar file sent to npm after. How this file is generated now ?

Thanks !

**Comment by Phanabani** [comment]
@oxyno-zeta Thank you! I've been working hard at this!

Regarding prettier, I had it installed in the root library while I was working on 3.0.0, but decided to remove it for 2.3.0 because I didn't want the git diffs to be huge (to make it easier for you to review). I figured a major refactoring like that would be better suited to a major version bump. If you'd like me to add it back for this version and run it on the core components, I'd be happy to! I also did leave prettier in the dev_app dependencies, since that was one of the main focuses of this update.

Regarding the npm publish tar file, I'll look into fixing that for you! I'll go back to read the old gulp files. I've never published to npm, so I didn't know what that involved. 😊

Thanks for the preliminary review!

**Comment by oxyno-zeta** [comment]
Just had the time to finally look at this.

Seems very cool !
I can't approve it because this is in draft but I'm ok with those changes.
That's a great work ! Thanks !

Regards,

Oxyno-zeta

**Comment by Phanabani** [comment]
@oxyno-zeta

Yay! Thank you for taking the time to review it. Whenever you're ready, we can merge and publish! Everything in my [top message](https://github.com/oxyno-zeta/react-editable-json-tree/pull/48#issue-1400467338) (from the changelog) can be copy/pasted as the release description. 😄

Also, whenever you have time, check out #52 so we don't have to see the scary red X as the build status. 😆

**Comment by oxyno-zeta** [comment]
This have been released !

**Pull request merged**
